language: python
python:
- '2.7'
- '3.5'
- '3.6'
install:
- pip install codecov
- pip install coverage
script:
- python ./ci_python/hello.py
- coverage run ./ci_python/test.py
after_success:
- codecov --token=054205c8-f49f-4857-aa8a-d6c33dbd38c9
deploy:
  provider: s3
  access_key_id: AKIAJWC7UX35FXU7QI5Q
  secret_access_key:
    secure: IJH7sR3ODajNrkMB+NXG9JiENDWwiJwNqHbv1OfIAHxrULAEA2rx848OdUIbxr8NEwUumsXtkv2ayVPafckzqMIRBxMpEbpmpPpJ3/rpeRIUpc31nyw70Hu8SmVLXd8jTEoUIk+GuP+NP+XRhEpGELO+nsTfgZFXSgqDfYX0aFXXGattjRY53zClh3AgDMBWz81wmLodxA6NftG9YE+ynUXb53Uu7FvRmm7p+qCtDFy6RZ2WcB7qYKmu/ytZiC6RO7cPWy9yaeQFqFjLnKeippwMyrnSD38Q8toUAQ0GP4b5OXKt3v6fvyPNkABIx6wsIFIcG8GNJiK/c0PVw+AqvoXWm8H3Eu6Rli2CHD2Uinjo2vSQU17tTfVTHJmyU6h92zEb2vzXNz+I2eeWKnFd+LKv0nY2KQHhNoiEcGqKj5Id1dTCCvmkhTmDuakFZsrxvARsB9UjDxN+Xp4C64OlH6A3sxru8z7Tvuo8RRw0HtgrXyBVN6vpZiabYJxnbR0tXmCVyw65G4dB5iQP6RoQLbgpGv3PcBc/WPM7UPh7k8lltc0ovQrhq4n2IdKLURfllbcJLGqagrWIRZIH2CKzXdOR5ku1uy2/S+SfWw7VKqusa7pDM/NgozAKyx+ydy25z6OQDHsguwpLWOCwsAIX1luxudwIfF24L5VLaKTJBc0=
  bucket: philam18-bucket1
  local-dir: s3_html
  region: us-east-2
